    File "exception_quine.py", line 1
        File "exception_quine.py", line 1
        ^
IndentationError: unexpected indent
